#-------------------------------------------------------------------------------
# Name:        module1
# Purpose:
#
# Author:      Bryce
#
# Created:     27/06/2016
# Copyright:   (c) Bryce 2016
# Licence:     <your licence>
#-------------------------------------------------------------------------------


def addDatabaseSchemas(Schema):
    # Configure marchmallow schema
    class DataSchema(Schema):
        keyid = fields.Int()
        aprf = fields.Int()
        apcallsign = fields.Str()
        apid = fields.Int()
        callsign = fields.Str()
        id = fields.Int()
        rtcsec = fields.Int()
        rtcmin = fields.Int()
        rtchour = fields.Int()
        rtcday = fields.Int()
        rtcdow = fields.Int()
        rtcmon = fields.Int()
        rtcyear = fields.Int()
        apgpsfix = fields.Int()
        aplatdeg = fields.Int()
        aplatdec = fields.Float()
        aplatdir = fields.Str()
        aplondeg = fields.Int()
        aplondec = fields.Float()
        aplondir = fields.Str()
        apaltitude = fields.Float()
        apaltunits = fields.Str()
        apspeed = fields.Float()
        aphdop = fields.Float()
        gpsfix = fields.Int()
        latdeg = fields.Int()
        latdec = fields.Float()
        latdir = fields.Str()
        londeg = fields.Int()
        londec = fields.Float()
        londir = fields.Str()
        altitude = fields.Float()
        altunits = fields.Str()
        speed = fields.Float()
        hdop = fields.Float()
        gpio0 = fields.Int()
        gpio1 = fields.Int()
        gpio2 = fields.Int()
        adc0 = fields.Int()
        adc1 = fields.Int()
        adc2 = fields.Int()
        adc3 = fields.Int()
        adc4 = fields.Int()
        adc5 = fields.Int()
        adc6 = fields.Int()
        adc7 = fields.Int()
        adc8 = fields.Int()
        apepoch = fields.Int()
        crc = fields.Int()
        packettype = fields.Int()
        destcallsign = fields.Str()
        destid = fields.Int()
        faradayport = fields.Int()
        skip = fields.Int()

    data_schema = DataSchema(many=True)

    # Configure marchmallow schema
    class scalingSchema(Schema):
        keyid = fields.Int()
        keyname = fields.Str()
        callsign = fields.Str()
        id = fields.Int()
        adc0m = fields.Float(default=3)
        adc0b = fields.Float()
        adc1m = fields.Float()
        adc1b = fields.Float()
        adc2m = fields.Float()
        adc2b = fields.Float()
        adc3m = fields.Float()
        adc3b = fields.Float()
        adc4m = fields.Float()
        adc4b = fields.Float()
        adc5m = fields.Float()
        adc5b = fields.Float()
        adc6m = fields.Float()
        adc6b = fields.Float()
        adc7m = fields.Float()
        adc7b = fields.Float()
        adc8m = fields.Float()

        adc8b = fields.Float()
        tempcal = fields.Float()

    scaling_schema = scalingSchema(many=True)

    # Configure marchmallow schema
    class scaledTelemetry(Schema):
        keyid = fields.Int()
        callsign = fields.Str()
        id = fields.Int()
        adc0scaled = fields.Float()
        adc1scaled = fields.Float()
        adc2scaled = fields.Float()
        adc3scaled = fields.Float()
        adc4scaled = fields.Float()
        adc5scaled = fields.Float()
        adc6scaled = fields.Float()
        adc7scaled = fields.Float()
        adc8scaled = fields.Float()
        paenable = fields.Int()
        lnaenable = fields.Int()
        hgmselect = fields.Int()
        mosfet = fields.Int()
        led1 = fields.Int()
        led2 = fields.Int()
        gpsreset = fields.Int()
        gpsstandby = fields.Int()
        button = fields.Int()
        gpio0 = fields.Int()
        gpio1 = fields.Int()
        gpio2 = fields.Int()
        gpio3 = fields.Int()
        gpio4 = fields.Int()
        gpio5 = fields.Int()
        gpio6 = fields.Int()
        gpio7 = fields.Int()
        gpio8 = fields.Int()
        gpio9 = fields.Int()


    scaledtelemetry_schema = scaledTelemetry(many=True)

    class faradaytelemetry(db.Model):
        __tablename__ = 'telemetry'
        keyid = db.Column(db.Integer, primary_key=True)
        faradayport = db.Column(db.Integer)
        packettype = db.Column(db.Integer)
        aprf = db.Column(db.Integer)
        apcallsign = db.Column(db.String(9))
        apid = db.Column(db.Integer)
        callsign = db.Column(db.String(9))
        id = db.Column(db.Integer)
        rtcsec = db.Column(db.Integer)
        rtcmin = db.Column(db.Integer)
        rtchour = db.Column(db.Integer)
        rtcday = db.Column(db.Integer)
        rtcdow = db.Column(db.Integer)
        rtcmon = db.Column(db.Integer)
        rtcyear = db.Column(db.Integer)
        apgpsfix = db.Column(db.Integer)
        aplatdeg = db.Column(db.Integer)
        aplatdec = db.Column(db.Float)
        aplatdir = db.Column(db.String(1))
        aplondeg = db.Column(db.Integer)
        aplondec = db.Column(db.Float)
        aplondir = db.Column(db.String(1))
        apaltitude = db.Column(db.Integer)
        apaltunits = db.Column(db.Float)
        apspeed = db.Column(db.Float)
        aphdop = db.Column(db.Float)
        gpsfix = db.Column(db.Integer)
        latdeg = db.Column(db.Integer)
        latdec = db.Column(db.Float)
        latdir = db.Column(db.String(1))
        londeg = db.Column(db.Integer)
        londec = db.Column(db.Float)
        londir = db.Column(db.String(1))
        altitude = db.Column(db.Integer)
        altunits = db.Column(db.Float)
        speed = db.Column(db.Float)
        hdop = db.Column(db.Float)
        gpio0 = db.Column(db.Integer)
        gpio1 = db.Column(db.Integer)
        gpio2 = db.Column(db.Integer)
        adc0 = db.Column(db.Integer)
        adc1 = db.Column(db.Integer)
        adc2 = db.Column(db.Integer)
        adc3 = db.Column(db.Integer)
        adc4 = db.Column(db.Integer)
        adc5 = db.Column(db.Integer)
        adc6 = db.Column(db.Integer)
        adc7 = db.Column(db.Integer)
        adc8 = db.Column(db.Integer)
        apepoch = db.Column(db.Integer)
        crc = db.Column(db.Integer)
        destid = db.Column(db.Integer)
        destcallsign = db.Column(db.String(9))

    class faradayscaling(db.Model):
        __tablename__ = 'faradayio'
        keyid = db.Column(db.Integer, primary_key=True)
        keyname = db.Column(db.String(25))
        callsign = db.Column(db.String(9))
        id = db.Column(db.Integer)
        adc0m = db.Column(db.Float)
        adc0b = db.Column(db.Float)
        adc1m = db.Column(db.Float)
        adc1b = db.Column(db.Float)
        adc2m = db.Column(db.Float)
        adc2b = db.Column(db.Float)
        adc3m = db.Column(db.Float)
        adc3b = db.Column(db.Float)
        adc4m = db.Column(db.Float)
        adc4b = db.Column(db.Float)
        adc5m = db.Column(db.Float)
        adc5b = db.Column(db.Float)
        adc6m = db.Column(db.Float)
        adc6b = db.Column(db.Float)
        adc7m = db.Column(db.Float)
        adc7b = db.Column(db.Float)
        adc8m = db.Column(db.Float)
        adc8b = db.Column(db.Float)
        tempcal = db.Column(db.Float)

    class faradayScaledTelemetry(db.Model):
        __tablename__ = 'scaledtelemetry'
        keyid = db.Column(db.Integer, primary_key=True)
        callsign = db.Column(db.String(9))
        id = db.Column(db.Integer)
        adc0scaled = db.Column(db.Float)
        adc1scaled = db.Column(db.Float)
        adc2scaled = db.Column(db.Float)
        adc3scaled = db.Column(db.Float)
        adc4scaled = db.Column(db.Float)
        adc5scaled = db.Column(db.Float)
        adc6scaled = db.Column(db.Float)
        adc7scaled = db.Column(db.Float)
        adc8scaled = db.Column(db.Float)
        paenable = db.Column(db.Integer)
        lnaenable = db.Column(db.Integer)
        hgmselect = db.Column(db.Integer)
        mosfet = db.Column(db.Integer)
        led1 = db.Column(db.Integer)
        led2 = db.Column(db.Integer)
        gpsreset = db.Column(db.Integer)
        gpsstandby = db.Column(db.Integer)
        button = db.Column(db.Integer)
        gpio0 = db.Column(db.Integer)
        gpio1 = db.Column(db.Integer)
        gpio2 = db.Column(db.Integer)
        gpio3 = db.Column(db.Integer)
        gpio4 = db.Column(db.Integer)
        gpio5 = db.Column(db.Integer)
        gpio6 = db.Column(db.Integer)
        gpio7 = db.Column(db.Integer)
        gpio8 = db.Column(db.Integer)
        gpio9 = db.Column(db.Integer)

def main():
    pass

if __name__ == '__main__':
    main()
